### ISSUE TITLE
[Crash] Crash instead of "Missing Mods" Screen

### ISSUE THREAD

**Issue by WenXin20** [SuperMartijn642/ScarecrowsTerritory#1]
**Version Info**
- `Minecraft v1.16.5`
- `Forge v36.0.1`
- `Scarecrow's Territory v1.0.1`

I didn't realize at first the this mod required the Config Lib mod, but instead of displaying the "missing mods" screen, the game crashed. I was looking to make sure I had used the latest file when I realized I had missed the required mod.

**Steps to Reproduce**
1. Install mod without Config Lib
2. Crash instead of seeing a "missing mods" screen

**Crash Report**
- [Crash Report](https://gist.github.com/WenXin20/d93bea9ed0f594de40267e32f8c52e77)

**Comment by SuperMartijn642** [comment]
Whoops, I probably messed something up then.

**Comment by SuperMartijn642** [comment]
Turns out I misspelled the modid for Scarecrow's Territory in the dependency.
It fixed it now 1.0.2.

Thank you for reporting it!
