### ISSUE TITLE
[Feature] Make scarecrow "count as carved pumpkin" so bird mods which use carved pumpkins as "scarecrows" are compatible!

### ISSUE THREAD

**Issue by Reshirou** [SuperMartijn642/ScarecrowsTerritory#10]
Like Alex's Mobs using carved pumpkins to scare off crows from crops

This is a cute utility that could also easily be used as an aesthetic item for that purpose too!

**Comment by SuperMartijn642** [comment]
I added all the scarecrows to the `crow_fears` tag from Alex's Mobs now in version 1.1.4 for Minecraft 1.14 to 1.18.

Thank you for the suggestion!
