### ISSUE TITLE
l

### ISSUE THREAD

**Issue by coldonx** [SuperMartijn642/ScarecrowsTerritory#11]

**Comment by coldonx** [comment]
i made a mistake

**Comment by SuperMartijn642** [comment]
Yeah, you want both the core and config lib 🙂

**Comment by coldonx** [comment]
> 

thank you, sorry about that - first time. I dont know how to delete this thread now

**Comment by SuperMartijn642** [comment]
No worries, as long as the issue is closed (like it is now) it's fine.
