### ISSUE TITLE
[Bug] Large numbers of hostile mobs spawning 1.18.1

### ISSUE THREAD

**Issue by InertiaImpact** [SuperMartijn642/ScarecrowsTerritory#12]
**Version Info**
- Minecraft, 1.18.1
- Forge, 39.0.10
- Scarecrow's Territory - scarecrowsterritory-1.1.3-mc1.18

**Description of the Bug**
When a scarecrow is placed and hostile mobs are eligible to spawn (night, grass), large numbers spawn. This seems to exceed the normal mob cap. 

Was able to reproduce within a single player world with just this mod installed(and dependencies w/ curseforge) but I also had it on a multiplayer server with other mods and this was happening aswell.

**Steps to Reproduce**
Place scarecrow in world, set to midnight. I was in creative.

**Screenshots**
![image](https://user-images.githubusercontent.com/25996712/148712650-9568c39e-3fa7-427a-983f-49a3ab62e0c3.png)

![image](https://user-images.githubusercontent.com/25996712/148712784-85e183ac-615e-45ab-b1d6-7049b70d7c66.png)

**Comment by matthewchanyy03** [comment]
Came here to report the same bug. I'm guessing its related to https://github.com/SuperMartijn642/ScarecrowsTerritory/issues/9

**Comment by InertiaImpact** [comment]
Any update on getting this one fixed?

**Comment by SuperMartijn642** [comment]
This issue requires some more work since mob spawning is different for pretty much every Minecraft version. I currently don't have much time available due to school, so it will have to wait for a bit longer.

**Comment by Yourname942** [comment]
Any updates on this issue? Thank you!

**Comment by Simba98** [comment]
The Minecraft spawning logics are different between Minecraft versions.
#22 would be a workaround, just disable it.

**Comment by SuperMartijn642** [comment]
I adjusted the calculation for the mob, so the issue should be fixed now.

It is available in Scarecrows' Territory 1.1.8.
Thank you for reporting the issue!
