### ISSUE TITLE
[Question] ... Does it allow grass to grow? 

### ISSUE THREAD

**Issue by ThePetePandaPablo** [SuperMartijn642/ScarecrowsTerritory#14]
**Question**
...
Does it allow grass to grow for something like a sheep wool farm? Thanks :)

**Comment by SuperMartijn642** [comment]
No, for grass to grow you only need a chunk loader from my Chunk Loaders mod.
https://www.curseforge.com/minecraft/mc-mods/chunk-loaders

**Comment by ThePetePandaPablo** [comment]
So I thought that too but when I was testing you're chunk mod I had no luck or any other chunk loader mod. All crops worked fine but the grass would not grow. I think the player has to be nearby unless I'm missing something? Will keep testing but this grass seems stubborn.

**Comment by SuperMartijn642** [comment]
All I can think of is that grass needs a certain light level, so if it is night time or just a dark area that might be the reason.

If that is not the problem, could you report it on the Chunk Loaders issue tracker with some screenshots?

**Comment by ThePetePandaPablo** [comment]
Ok will do, I will also test with a fresh install

**Comment by SuperMartijn642** [comment]
I will close this issue as it is no longer related to Scarecrows' Territory. Be sure to report the issue to the Chunk Loaders repository if it persists.
