### ISSUE TITLE
[Crash] Quark mod isn't compatible with this mod?

### ISSUE THREAD

**Issue by mrstealyob** [SuperMartijn642/ScarecrowsTerritory#16]
Version Info
- Minecraft, 1.18.2
-Scarecrows' Territory 1.1.5 for Forge 1.18

**Steps to Reproduce**
Install mod, place in mod folder along with quark mod,
start the launcher through curseforge... failed

**Crash report (~/logs/latest.log)**
https://pastebin.com/BxJbpqw3

**Comment by SuperMartijn642** [comment]
Thank you for reporting the issue.

I tested it with Quark, Scarecrows' Territory and their dependencies installed and Minecraft starts up without any issues.
Are you sure it is just Quark and Scarecrows' Territory which cause the crash?

**Comment by mrstealyob** [comment]
> 

Yeah, i even have the required dependencies downloaded. and this still shows up

![crash](https://user-images.githubusercontent.com/35870765/168873187-a09d2226-53f9-4dcc-88a0-daaffccd892d.PNG)
![mods](https://user-images.githubusercontent.com/35870765/168873235-5760a2a8-8ad9-4101-8b3b-0094f352a202.PNG)

**Comment by mrstealyob** [comment]
however, I'm not too sure if there's something else interfering with this problem.

**Comment by SuperMartijn642** [comment]
Quark also lists AutoRegLib as a dependency. You don't seem to have that installed, so that might be the problem. If it is, Quark should definitely add that as a dependency to their mod file though, instead of just crashing.
![image](https://user-images.githubusercontent.com/12382965/168874536-967e3e23-344a-4733-b339-f957f2932a05.png)

**Comment by mrstealyob** [comment]
i've found the solution, it seems like there was some other mod called "pigsteal" interfering with these mods, everything seems to works smoothly now. Thanks for your time!
