### ISSUE TITLE
[Bug] Doesn't stop mobs despawning

### ISSUE THREAD

**Issue by jlaine3333** [SuperMartijn642/ScarecrowsTerritory#17]
**Version Info**
- Minecraft, 1.18.2
- Scarecrow's Territory, 1.1.5 forge

**Description of the Bug**
Leaving the radius for hostile mobs to despawn still forces them to despawn despite having a scarecrow in the area. Chunks are still loaded in, but I used the recommended chunkloader mod too just to make sure, and it still happens regardless.

**Steps to Reproduce**
1. Place a scarecrow
2. Walk ~128 blocks from the scarecrow
3. All hostile mobs will despawn near the scarecrow. Xaero's minimap makes it easy to visualize if need be.

**Comment by SuperMartijn642** [comment]
I cannot reproduce this issue. Whether the chunk is chunk loaded or not, creepers, zombies, and skeletons do not despawn when moving away and going back.

This is likely caused by some other mod you're using.
