### ISSUE TITLE
[Bug] Scarecrows don't work when in another dimension

### ISSUE THREAD

**Issue by cimdy** [SuperMartijn642/ScarecrowsTerritory#18]
**Is your feature request related to a problem? Please describe.**
When I use chunkloader, in the dimension without player，mobs can't spawn, unless there is a spawner, maybe this is a bug

**Describe the solution you'd like**
I hope that when I am in "the nether", the "swamphut" of "over world" will also spawn "witch". I think it will be cool

**Comment by SuperMartijn642** [comment]
This is definitely a bug, since I tested specifically for this so it should work. What version of Minecraft and Scarecrows' Territory are you using?

**Comment by cimdy** [comment]
Thank you for your reply！

Version Info
Minecraft, 1.18.2
Forge, 40.1.60
scarecrowsterritory-1.1.5-forge-mc1.18
chunkloaders-1.2.0-forge-mc1.18

**Comment by SuperMartijn642** [comment]
I fixed it now in Scarecrows' Territory 1.1.8.

Thank you for reporting the issue!
