### ISSUE TITLE
[Bug] Server Hang

### ISSUE THREAD

**Issue by WenXin20** [SuperMartijn642/ScarecrowsTerritory#2]
**Version Info**
- `Minecraft v1.16.5`
- `Forge v36.0.1`
- `Scarecrow's Territory v1.0.1`
- `Config Lib v1.0.1`

Hello, I've got another issue. With the mod loaded on a server, the world hangs while loading and never makes it past 100%. If I remove the scarecrow mod, the world immediately loads after reaching 100%.

**Steps to Reproduce**
1. Install mod with Config Lib
2. Load world

**Logs**
- [Debug.log](https://gist.github.com/WenXin20/d47cb03cd53f3322767e786cfb13aea9)
- [Latest.log](https://gist.github.com/WenXin20/cd0fa5a134181f3437dc9489014abe04)

**Comment by SuperMartijn642** [comment]
It doesn't happen when I'm using just Scarecrow's Territory. Could you share a screenshot of the mods you're using or a pack name if its publicly available?

**Comment by WenXin20** [comment]
Here's a link to it, its a wip pack that I'm making: https://drive.google.com/file/d/1nq_hxLftAoLLM9SP-9JwMetjJwxyNkD4/view?usp=sharing

**Comment by SuperMartijn642** [comment]
It appears to be some issue in combination with Quark. If a add just Quark, AutoRegLib, Config Lib, and Scarecrow's Territory a world can no longer be generated.
I have a fix for it now, but I'm still not sure what the underlying issue is.

I will investigate more tomorrow.

**Comment by WenXin20** [comment]
Oh, interesting. I installed Lava Dynamics too, and that mod also has the same problem with Quark too apparently:

https://gitlab.com/kreezxil/Lava-Dynamics/-/issues/37#note_491190514

**Comment by WenXin20** [comment]
And to clarify, I tested that mod and this one separately.

**Comment by FynnWaelsing** [comment]
Just jumping in to state that I'm getting the same issue. I added this mod to a pre-existing world, and the game would freeze up whenever I started exploring new chunks, and trying to generate a new world stayed at 100% until I removed this mod. Here is my mod list, which does also include Quark.

![image](https://user-images.githubusercontent.com/45303748/105440725-188f5200-5c35-11eb-935f-04bfa4ae56e2.png)

**Comment by SuperMartijn642** [comment]
It appears its an issue with Quark.
I've created an issue report [here](https://github.com/Vazkii/Quark/issues/2922). Its up to Quark to fix it now.

In the meanwhile I will upload version 1.0.3 for Scarecrow's Territory, which temporarily fixes the world not loading.

**Comment by BBoldt** [comment]
I was wondering what recently added mod to my pack was causing this haha, I had it narrowed down to like 5 or 6 mods but couldn't find the combination that was doing it.

Thanks for the fix! Great mod.

**Comment by WenXin20** [comment]
Thanks!
