### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by Arthurlelynx** [SuperMartijn642/ScarecrowsTerritory#20]
**Version Info**
- Minecraft, 1.19.2
- Scarecrow's Territory, 1.1.6

**Steps to Reproduce**
the game launch correctly but if i place a scarecrow the game crash

**Crash report (~/logs/latest.log)**
...
[crash-2023-01-15_18.20.32-server.txt](https://github.com/SuperMartijn642/ScarecrowsTerritory/files/10420813/crash-2023-01-15_18.20.32-server.txt)

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.1.6a.

Thank you for reporting the issue!
