### ISSUE TITLE
[Bug] Textures missing

### ISSUE THREAD

**Issue by kaz880** [SuperMartijn642/ScarecrowsTerritory#25]
**Version Info**
- Minecraft 1.19.2
- Scarecrow's Territory, Fabric, 1.19.2

**Description of the Bug**
Whenever we try to put down or craft the scarecrows, they don't have any texture on them. They just show up in pink and black.

**Screenshots**
![image](https://github.com/SuperMartijn642/ScarecrowsTerritory/assets/112892936/be0cdcf0-6030-4a02-9f6d-e10fd432e5ad)
![image](https://github.com/SuperMartijn642/ScarecrowsTerritory/assets/112892936/3869a14d-1dfd-4b2f-9426-fd6c32cb5f06)
![image](https://github.com/SuperMartijn642/ScarecrowsTerritory/assets/112892936/fbd91017-7757-48f4-a10f-6aae7eedb27f)

**Comment by SuperMartijn642** [comment]
Seems to work fine with just Scarecrows' Territory, so likely some other mod you have installed breaks it:
![image](https://github.com/SuperMartijn642/ScarecrowsTerritory/assets/12382965/d29d370c-115b-40c6-a7d1-5bba7235f0e6)

If you are using ThonkUtil, that is probably the cause. They break any model not in a subfolder. They fixed it for newer Minecraft versions but don't seem to wanna fix it on older ones.

If you are not using ThonkUtil or that is not the cause, please narrow down which other mods are needed to reproduce the issue.

**Comment by kaz880** [comment]
We do have ThonkUtil, is there a known work around instead of removing it?

**Comment by SuperMartijn642** [comment]
Not that I know of, just ask them 🤷‍♂️

**Comment by kaz880** [comment]
We removed it and the associated mods and it worked, thank you :)
