### ISSUE TITLE
[Crash] Mod Fails to Load on Dedicated Server

### ISSUE THREAD

**Issue by Darkosto** [SuperMartijn642/ScarecrowsTerritory#30]
**Version Info**
- Minecraft: 1.20.1
- Scarecrow's Territory: 1.1.11c

**Steps to Reproduce**
I've added the mod to a dedicated server to test and am getting a crash report that the mod has failed to load.

**Crash report (~/logs/latest.log)**
https://gist.github.com/Darkosto/775e7ad7e592775ab14c1a3848712a6b

**Comment by SuperMartijn642** [comment]
Should be fixed now in version 1.1.11d for Forge 1.20.1.
Thank you for reporting the issue!
