### ISSUE TITLE
[Bug] Scarecrow doesn't activate spawners moved/created by "Spawners Plus"

### ISSUE THREAD

**Issue by t-Ghost-t** [SuperMartijn642/ScarecrowsTerritory#33]
**Version Info**
- Minecraft, 1.20.1 Fabric 0.15.6
- Scarecrow's Territory, 1.1.11 Fabric
- Spawners Plus: 3.0: https://modrinth.com/mod/spawners_plus

**Description of the Bug**
... Scarecrow does not keep Spawner's Plus created mob spawners active. 

**Steps to Reproduce**
... Craft an inactive spawner, use a mob soul on it, place scarecrow nearby, walk out of spawning range. Nothing will spawn.

**Screenshots**
... N/A

**Comment by t-Ghost-t** [comment]
![Screenshot 2024-02-27 133431](https://github.com/SuperMartijn642/ScarecrowsTerritory/assets/102787026/bf592d7a-3c6c-4e7b-96ac-98d84617fc50)

**Comment by t-Ghost-t** [comment]
Sorry for the spam/confusion, but for whatever reason it seems like restarting my server caused it to start working so maybe it's an inconsistent/intermittent issue.

**Comment by SuperMartijn642** [comment]
Seems Scarecrows' Territory keeps track of all spawners which get placed or when a chunk gets loaded. Looking at the source code for Spawners+, it seems they simply set the block to a spawner when right-clicking on an inactive spawner with a mob soul. Likely this wasn't detected by Scarecrows' Territory, hence no mobs would spawn from it.
After unloading and re-loading the chunk Scarecrows' Territory would have detected the spawner and thus it would start working.

Coincidentally, I reworked the spawner handling in Scarecrows' Territory version 1.1.11a, removing the need to keep track of spawners at all. Thus, this issue should be fixed when updating to version 1.1.11a.
Thank you for reporting the issue!
