### ISSUE TITLE
[Crash] game crashes when loading with this mod

### ISSUE THREAD

**Issue by Rowanh16** [SuperMartijn642/ScarecrowsTerritory#35]
**Version Info**
- Minecraft, 1.20.1
- Scarecrow's Territory, 1.1.10 forge

**Steps to Reproduce**
add mod to mods folder
load minecraft as usual
crashes

**Crash report (~/logs/latest.log)**
https://pastebin.com/hnVSRNDR

not sure if this is right let me know if i need to add more info/change anything. another thing to note is im using the swem starter modpack. its been working fine but then i added the mod and now minecraft crashes. so it could be that its just clashing with another mod but i dont know.

**Comment by SuperMartijn642** [comment]
You need to install the dependencies for Scarecrows' Territory.
Normally Forge would show you a warning screen explaining so, however it seems nochatreports makes that warning screen crash.
