### ISSUE TITLE
[Bug] Either the scarecrows mod, or the chunk loaders mod, isnt working

### ISSUE THREAD

**Issue by Eazy1872** [SuperMartijn642/ScarecrowsTerritory#36]
**Version Info**
- Minecraft, Forge 1.20.4
- Scarecrows' Territory 1.1.11e for Forge 1.20
- 
**Description of the Bug**
Either one of the two mods aren't working, anytime i go to my xp grinder, 0 mobs are there, either the chunk loader isnt keeping chunks loaded, or the scarecrow isnt keeping the spawner active.

**Steps to Reproduce**
Load mod, play game, no mobs spawn at spawner

**Screenshots**
[...
](https://gyazo.com/812b860cf26112636ef2ee1b1675a13e)
https://gyazo.com/6066012940ba2543eba421db3ab3cb7f

Those gyazo's are a full list of mods i am using.

**Comment by SuperMartijn642** [comment]
Can you please describe or share some screenshots of what you are trying to do? What is your setup like?

And can you check whether it's the chunk loader not working or it's the scarecrows not working?

**Comment by Eazy1872** [comment]
So after further playing with the mods active, it appears that as long as I am in the overworld, the chunks or scarecrow isnt working.

However, when I am in the nether, the grinder is definitely producing zombies as when I arrive back, they are there.

So this would perhaps mean that the mods are working, both, however they dont work when I am in the overworld.

Before downloading the mods, i removed any mods from my mod list that would do anything towards entities,

The grinder is a very basic one, just a zombie spawner that shoots the zombies up then drops them to a small amount of health, ive included some screenshots of the setup with the scarecrow and the chunk loader.

I have optifine on, but the chunks settings are made in a way that shouldnt effect entities. 

It it is clear that the mods do work when i am in the nether, i have been to the nether 3 times and have came back to mass amounts of zombies, however i just spent around an hour and a half running around the overworld and came back to nothing.
![2024-06-03_01 49 01](https://github.com/SuperMartijn642/ScarecrowsTerritory/assets/164068556/0b4b4bff-a44b-4ed6-a1b8-b468b0fa587f)
![2024-06-03_01 49 08](https://github.com/SuperMartijn642/ScarecrowsTerritory/assets/164068556/a4bc4c1e-485b-4cf7-8d9b-52ffe7f26d60)
![2024-06-03_01 49 12](https://github.com/SuperMartijn642/ScarecrowsTerritory/assets/164068556/5cc76df4-8e93-481e-83e4-9416056fd917)

**Comment by SuperMartijn642** [comment]
> as long as I am in the overworld, the chunks or scarecrow isnt working.

Could you check whether the chunk loader is working, so we can narrow down the problem to just one of the two?

The scarecrow activates spawners, but also allows for passive mob spawning. It could be that the spawner is not doing anything at all and the mobs you see after returning from the nether spawned passively. The lack of mobs when you are in the overworld could then be explained by the mob cap being filled from mobs near you.
To check whether the spawner is actually spawning mobs, you could place something which prevents passive mob spawning like water. If you cover the floor with water and there are now no mobs when returning from the nether, that means the spawner is not working and the mobs just spawned passively.

Also, are you using any mods that affect spawners?

> I have optifine on, but the chunks settings are made in a way that shouldnt effect entities.

I have had many people report issues with entities in chunk loaded chunks when using OptiFine. Not sure if OptiFine is affecting anything here though.
