### ISSUE TITLE
stuck on 98% when creating new world when using this mod

### ISSUE THREAD

**Issue by AdnanuReeves** [SuperMartijn642/ScarecrowsTerritory#4]
I get stuck on 98% sometimes 96% when I try to use this mod and make a new world. As soon as I remove it everything works fine.

**Comment by SuperMartijn642** [comment]
Are you using Quark? If so this is an Quark issue as discussed here #2.
Version 1.0.3 will temporarily fix this.

**Comment by SuperMartijn642** [comment]
I assume that was the same problem then.
If not, feel free to comment and I will reopen the issue.
