### ISSUE TITLE
[Crash] Scarecrow Block Crash

### ISSUE THREAD

**Issue by WenXin20** [SuperMartijn642/ScarecrowsTerritory#5]
**Version Info**
- `Minecraft v1.16.5`
- `Forge v36.0.7`
- `Scarecrow's Territory v1.0.4`
- `Config Lib v1.0.2`

**Steps to Reproduce**
- After updating config lib, I got this crash on launch

**Crash report (~/logs/latest.log)**
- [Crash Report](https://gist.github.com/WenXin20/a4ed2dc5015f1906626d5d09f5727491)

**Comment by SuperMartijn642** [comment]
I fixed it now in Config Lib version 1.0.3.

Thanks for reporting the issue!

**Comment by WenXin20** [comment]
Alright, thanks!
