### ISSUE TITLE
[Crash] Duplicate Mod Error on server

### ISSUE THREAD

**Issue by Hate9** [SuperMartijn642/ScarecrowsTerritory#6]
**Version Info**
- Minecraft 1.12.2,
- Scarecrow's Territory 1.0.4,

**Steps to Reproduce**
Install the mod on a server
Start the server

**Crash report (~/logs/latest.log)**
https://pastebin.com/zJQh6VDB
https://pastebin.com/Skz8pA22

**Comment by SuperMartijn642** [comment]
I fixed it now in version 1.0.4a for Minecraft 1.12.

Thank you for reporting the issue!
