### ISSUE TITLE
[Crash] Game doesn't run the mod at all in 1.16.5. Minecraft crashes on opening, saying the mod is outdated.

### ISSUE THREAD

**Issue by MiniPenguinGaming** [SuperMartijn642/ScarecrowsTerritory#7]
**Version Info**
- Minecraft, ...
- Scarecrow's Territory, ...

**Steps to Reproduce**
...

**Crash report (~/logs/latest.log)**
...

**Comment by SuperMartijn642** [comment]
Can you fill in the report?

Do you have the file for 1.16.5?

**Comment by SuperMartijn642** [comment]
I can't help without more info.
Feel free to comment and I will reopen the issue.

**Comment by MiniPenguinGaming** [comment]
Yes, I have the file for 1.16.5. But everything I try to run minecraft, the
mod crashes and doesn't let me play the game with the mod.

**Comment by SuperMartijn642** [comment]
Can I have the crash report, the ~/logs/latest.log file as specified in the report template?

**Comment by SuperMartijn642** [comment]
I can't help without the basic info as requested in the template, which you still haven't filled in.

**Comment by Bi0haze** [comment]
Hey 
I have kind of the same problem but for me it says 
"Mod Scarecrowsterritiry requires supermartijn642configlib 1.0.5 or above Currently, supermartijn642configlib  is not installed 
Mod Scarecrowsterritiry requires supermartijn642configlib 1.0.1 or above, and below 1.1.0" 

did i forgot something?
